### PR TITLE
Fixed email verification bug when using admin_email

### LINKED ISSUE #65: Says username and email is in use when nothing is in database
I keep getting the issue in my register form saying that the username or email is already in use.  
What do I need to do to fix it.
The table I am entering values into is empty so this issue shouldn't be happening.

### LINKED ISSUE #71: Multiple tile enters same email
while sign-up it tries to enter same email address multiple time so always give same error username or email already exists.

### PR DESCRIPTION
**Pull request by foxxlpaul**
Closes #71 Closes #65

### CODE REVIEW

**Comment by foxxlpaul** [comment]
About commit c80be44:
Many hosting providers provide email functionality on Host=localhost Port=25 Authentication=no
This update fixes a bug when not using authentication (making it configurable in config.php) and disables opportunistic TLS to fix SSL mismatch when using localhost as Host.

**Comment by foxxlpaul** [comment]
@JohnBisson you have to download and install phpmailer into /login/scripts/phpmailer directory https://github.com/fethica/PHP-Login/tree/master/login/scripts

**Comment by JohnBisson** [comment]
Thanks.  I'm not new to programming but I a very new to git. I downloaded the zip, do I just copy .php files into scripts folder or is there more to 'installation' (as I suspect)?
Thanks
JohnB

**Comment by tomcatbuzz** [comment]
You can just put the files there manually if you have access.

**Comment by JohnBisson** [comment]
I did that and thanks for your quick response. errror msg gone but email not sending -- probably a smpt setting or other that I can play with.


Thanks Again,


JohnB

________________________________

**Comment by tomcatbuzz** [comment]
Actually, I was trying to test the email send also because I was playing around with that module and it is completely broken for sending emails, my opinion any how. It puts a user in the DB but never sends a user email or admin mail. I configured it as per many directions given to others. But I am running off a localhost, that might be an issue, but if it is going to smtp mailservers it should not matter what platform it is sending from. I have gone in the DB and manually verified my user credentials to check the login in portion for testing. You just change the O to a 1, But, I think you knew that already.
Tony
    On Wednesday, November 22, 2017, 12:51:32 AM EST, JohnBisson <notifications@github.com> wrote:  
 
 I did that and thanks for your quick response. errror msg gone but email not sending -- probably a smpt setting or other that I can play with.


Thanks Again,


JohnB

________________________________

**Comment by foxxlpaul** [comment]
Hello @tomcatbuzz and @JohnBisson you might be interested in the Laravel framework, I think it's a better solution than this PHP-Login script. Laravel is a beautiful framework with also a simple login and register functionality: https://laravel.com/docs/5.5/authentication#authentication-quickstart (see also this video: https://laracasts.com/series/laravel-from-scratch-2017/episodes/17)

**Pull request closed without merging**
