### PR TITLE
Major additions

### PR DESCRIPTION
**Pull request by therecluse26**
Added password hashing for security, signup form with both client and server-side validation, new user verification and confirmation emails, the ability for admins to confirm users or users to confirm themselves, database integrity additions such as GUIDs and time stamping. Also updated the README documentation to reflect these changes.

### CODE REVIEW

**Comment by fethica** [comment]
Thank you for this great contribution :+1:

**Comment by therecluse26** [comment]
No problem, glad I could help! Do you know though why I'm not showing up as a contributor? :/

**Comment by fethica** [comment]
I have no idea ! Could I add you as a member to the repo so we can maintain this project together ?

**Comment by therecluse26** [comment]
Absolutely!

**Comment by fethica** [comment]
Done ! thank you :)

**Comment by bercanozcan** [comment]
Good job.

**Comment by therecluse26** [comment]
@bercanozcan Thank you!

**Pull request merged**
